# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'foo', 'Card']

# %% ../00_card.ipynb 4
from fastcore.utils import *

# %% ../00_card.ipynb 5
def foo(): pass

# %% ../00_card.ipynb 6
suits = ["♣️","♦️","♥️","♠️"]
ranks = [None,"A"] + [str(x) for x in range(2,11)] + ["J", "Q", "K"]

# %% ../00_card.ipynb 17
class Card:
    "트럼프 카드"
    def __init__(self,
                 suit, # `suits`에 들어가는 인덱스
                 rank): # `ranks`에 들어가는 인덱스
        self.suit, self.rank = suit, rank
        #print(1/0)
    def __str__(self): return f"{suits[self.suit]}{ranks[self.rank]}"
    __repr__ = __str__
    # def __eq__(self, a:'Card'): return (self.suit,self.rank) == (a.suit,a.rank) 

# %% ../00_card.ipynb 30
@patch
def __eq__(self:Card, a:Card): return (self.suit,self.rank) == (a.suit,a.rank) 

# %% ../00_card.ipynb 33
@patch
def __lt__(self:Card, a:Card): return (self.suit,self.rank) < (a.suit,a.rank) 
